[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs@18", "yarn"]

[build.nixpacksPlan.phases.install]
cmds = ["yarn install"]

[build.nixpacksPlan.phases.build]
cmds = ["yarn build"]

[start]
cmd = "yarn migrations:run && yarn start"
